#!/bin/bash
echo "Скрипт"
mkdir main_folder
cd main_folder
mkdir first_folder second_folder third_folder
cd first_folder
touch 1.txt 2.txt 3.txt 1.json 2.json
mkdir four_folder five_folder six_folder
mv 1.json 1.txt five_folder
